name: watchtower_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - tabulate>=0.8.0
  - pip
  - pip:
    - tabulate>=0.8.0 